#!/bin/bash

curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -

sudo apt update 

sudo apt install -y nodejs

sudo npm -g install create-react-app 

create-react-app myapp 

cd myapp ;  npm start 

